[package]
name = "dbreboot"
version = "0.1.0"
authors = ["The ThreefoldTech developers <info@threefold.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53"
cc = "1"
protoc-rust-grpc = "0.6.2"
