[package]
name = "dbreboot"
version = "0.1.0"
authors = ["The ThreefoldTech developers <info@threefold.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bcdb"
path = "src/server.rs"

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
bindgen = "0.53"
cc = "1"
tonic-build = "0.2"
